concourse/s3-resource

Godeps/Godeps.json
Godeps/_workspace/src/github.com/concourse/s3gof3r/putter.go
README.md
cmd/check/main.go
cmd/in/main.go
cmd/out/main.go
models.go
out/out_command.go
s3client.go

Adds an option to specify a custom S3 compatible endpoint.
Additionally there's also an option to disable md5 hash checking on files, as some S3 providers might have a problem with this. (Mine did) 
Relies on this PR concourse/s3gof3r/pull/1
Default behaviour for AWS stays the same as before.
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>

add endpoint option for S3 compatible providers

---

README.md

Fix typo in example resource config

---

integration/integration_suite_test.go
integration/out_test.go
s3client.go

This change adds support for non-ssl s3 endpoints. It also forces path-style for easier setup for local development.

Support local s3 for development

---

build.yml

Test failed if we don't use standard region, because the endpoint is different.
The test already support custom endpoint, but the env. variable `S3_ENDPOINT` is not pass to the one-off task "build.yml"
Just adding the possibility to pass it. 
```bash
Expected
<in.InResponse>: {
Version: {
Path: "",
VersionID: "ooPCrMNmcfmoUCBVrE8HbTUDLfaU4ErS",
},
Metadata: [
{Name: "filename", Value: "some-file"},
{
Name: "url",
Value: "https://s3-ap-northeast-1.amazonaws.com/XXXX-gwenn-dedicated-version/in-request-files-versioned/some-file?versionId=ooPCrMNmcfmoUCBVrE8HbTUDLfaU4ErS",
},
],
}
to equal
<in.InResponse>: {
Version: {
Path: "",
VersionID: "ooPCrMNmcfmoUCBVrE8HbTUDLfaU4ErS",
},
Metadata: [
{Name: "filename", Value: "some-file"},
{
Name: "url",
Value: …
```

Adding S3_ENDPOINT to be pass to the job

---

README.md
cmd/check/main.go
cmd/in/main.go
cmd/out/main.go
fakes/fake_s3client.go
integration/integration_suite_test.go
integration/out_test.go
out/models.go
out/out_command.go
out/out_command_test.go
s3client.go

* this change will allow you to specify a [canned acl](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html)
that will be applied to the uploaded file.
This feature is useful when you want to publish objects and make them public immediately.
**TODO**
Attached is what the **Permissions** should look like (if specifying `acl: public-read`) in the web console:

Create an acl param for puts

---

README.md
cmd/check/main.go
cmd/in/main.go
cmd/out/main.go
integration/integration_suite_test.go
models.go
s3client.go

Minio doesn't provide a HTTPS endpoint. This is also not required when running everything on-site. Therefor disabling SSL (already provided by the AWS sdk) is an easy solution.

Add disableSSL for s3 compatible providers without SSL endpoints

---

fakes/fake_s3client.go
integration/check_test.go
integration/in_test.go
integration/s3client_test.go
models.go
out/out_command.go
s3client.go

Helpful for users who have to use encryption for compliance purposes,
such as cloud.gov.

Accept encryption options from source.

---

README.md
cmd/in/main.go
in/in_command.go
in/in_command_test.go
integration/in_test.go
integration/out_test.go
s3client.go

- the core functionality is that it allows the bucket name
to be prepended to the hostname (e.g. `dulfnruy35dwq.cloudfront.net`)
instead of default to the path (e.g. `cloudfront.net/dulfnruy35dwq`)
- particularly effective when downloading assets from an
unstable network (i.e. AWS China)
- this should not be confused with the `cloudfront_url` flag,
which modifies the URL being outputted but does not affect
the URL used to check/in/out.
```yaml
source:
bucket: dulfnruy35dwq
endpoint: cloudfront.net
force_path_style: false
```
Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>
[#129581055](https://www.pivotaltracker.com/story/show/129581055)

Add `virtual_hosted_style` flag to allow interactions with CloudFront

---

README.md
cmd/check/main.go
cmd/in/main.go
cmd/out/main.go
integration/integration_suite_test.go
models.go
s3client.go
v2signer.go

adds v2 signature signing for S3 compatible provides that do not support v4.
also does retries in case of multipartupload failures, as the s3manager does not handle that by himself.

add v2 signature signing, retry in case of multipartupload failures

---

README.md

Dependencies are already included in the repo.

Delete instructions for getting dependencies

---

fakes/fake_s3client.go
integration/check_test.go
integration/in_test.go
integration/out_test.go
integration/s3client_test.go
out/models.go
out/out_command.go
out/out_command_test.go
s3client.go
scripts/test

Based on a suggestion in https://github.com/concourse/s3-resource/pull/52 , we refactored the UploadFile parameters to use a struct for the option list.

Added the option to set the content-type metadata when uploading a file

---

integration/integration_suite_test.go

Are there any test suites that rely on the behavior of $S3_ENDPOINT defaulting to `https://s3.amazonaws.com` if it's not set?
When running the tests locally, if this variable is not set, you get a
test failure that's very tricky to spot. This should highlight it.
If $S3_ENDPOINT is unset/empty, you get:
```
Expected
<in.InResponse>: {
Version: {
Path: "",
VersionID: "yMOjcgIH.ioLfj2FTOGQshUrqnkI00_o",
},
Metadata: [
{Name: "filename", Value: "some-file"},
{
Name: "url",
Value: "https://s3-us-west-2.amazonaws.com/s3-resource-ginkgo-test-bucket-versioned/in-request-files-versioned/some-file?versionId=yMOjcgIH.ioLfj2FTOGQshUrqnkI00_o",
},
],
}
to equal
<in.InResponse>: {
Version: {
Path: "",
VersionID: "yMOjcgIH.ioLfj2FTOGQshUrqnkI00_o",
},
Metadata: [
{Name: "filename", Value: "some-file"}, …
```

Check S3_ENDPOINT before integration test run

---

s3client.go

- Attempting to upload a file to Google Cloud Storage larger than 5 MB
(the default multipart upload size) will return:
```
error running command: InvalidArgument: Invalid argument.
status code: 400, request id:
```
- This PR avoids the issue by disabling multipart uploads when the GCS
endpoint is used, didn't have time to investigate an actual fix or root cause.
- Didn't add an integration test as it seemed like a lot of overhead to
require a GCS account in CI just for this change, but let me know if
you'd rather have integration coverage around this.

Sidestep multipart upload failures on GCS

---

README.md
cmd/check/main.go
cmd/in/main.go
cmd/out/main.go
models.go
s3client.go

`disable_ssl` supports http endpoints but does not disable validation for https endpoints using self-signed certs.
This commit adds a new source configuration parameter `skip_ssl_verification`.

add skip_ssl_verification source configuration parameter

---

README.md
in/archive.go
in/in_command.go
in/in_command_test.go
in/models.go

When `unpack` is true and the file can be determined to be an archive it knows how to handle, the resource will unpack the archive to the destination directory after downloading it.
The way it works is by downloading the file the destination dir when the flag is set, and then if it's an archive it extracts it. If the archive is a .tar.gz it will unpack the tar after gunzipping it. The original archive is not saved.
This _should_ mean that when the `unpack` option is used the unpacked archive is cached in baggageclaim, which can be a benefit when downloading large zip files that get unpacked multiple times by different jobs.
This should also mean that this resource can be used as  an `image_resource`[*](https://github.com/concourse/concourse/issues/1369), where your archive lays out the …

Add unpack ability

---

in/archive.go

This basically restores the archive code to the way it was.

Don't read entire file into memory to check mime

---

README.md
check/command.go
check/command_test.go
in/command.go
in/command_test.go
integration/in_test.go
models.go

As described in https://github.com/concourse/s3-resource/issues/21, it would be helpful if S3 resources could be configured to be available even if they do not yet exist in S3. This PR adds parameters to support that.
For S3 versioning, the `initial_version` parameter describes what the version available should be named if the file does not exist in your S3 bucket.
For filepath-based versioning, the `initial_path` parameter describes the path to use if there are no regex matches in your S3 bucket.
A missing S3 resource will be empty by default, but you can specify content for it. `initial_content_text` allows specifying text content, or base64-encoded content can be provided to `initial_content_binary`.

Add ability to initialise non-existent resources

---

.dockerignore
README.md
cmd/check/main.go
cmd/in/main.go
cmd/out/main.go
models.go
s3client.go

* Allows EC2Role creds for Concourse running in AWS
_Note:_ It looks like `go fmt` modified a few extra lines.
```
Ran 0 of 29 Specs in 0.012 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 29 Skipped PASS
Running Suite: Out Suite
========================
Random Seed: 1522091803
Will run 20 of 20 specs
••••••••••••••••••••
Ran 20 of 20 Specs in 0.015 seconds
SUCCESS! -- 20 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
Running Suite: Versions Suite
=============================
Random Seed: 1522091803
Will run 22 of 22 specs
••••••••••••••••••••••
Ran 22 of 22 Specs in 0.007 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
Removing intermediate container 462b74b81892
---> 2e399e4a2b5e
Step 25/25 : FROM resource
---> e6120f6a912d
Successfully built e6120f6a912d …
```

Add chained credentials

---

README.md
in/command.go
in/command_test.go
models.go

Adding skip_download param on the resource to not download file on
resource get.
Useful only trigger the pipeline without using the object.

in: fix #95 add an option to not download the s3 file

---

README.md
in/command.go
in/command_test.go
in/models.go

skip_download can be defined globaly in the source configuration but for
specific usecase we might need to apply or override it only on few gets.
skip_download have been added on get params.
Defined as string in order to have 3 stats : 
* not defined : that means we keep the global value
* false : force to false/download for the specific get
* true : force to true/skipdownload for the specific get

in: add skip_download override param by get

---

s3client.go

Currently, this resource's check function throws an error when working with ECS.  ECS is an S3-compliant object store from Dell EMC (more info [here](https://www.dellemc.com/en-us/storage/ecs/index.htm#collapse)).  Check throws the following error:
```bash
resource script '/opt/resource/check []' failed: exit status 1
stderr:
[31merror finding versions: InvalidArgument: Invalid Argument
status code: 400, request id: 0ac6640d:1635ec685dc:834e8:55, host id: 
[0m
```
This is a simple fix to eliminate that error when interacting with ECS buckets.

Fixing a bug that prevents resource from working with Dell EMC ECS object store

---

README.md
models.go
out/command.go
out/command_test.go
s3client.go

Hi.
I enable to prevent multipart upload.
Users who use object storage which does not support multipart upload will be helpful.

Enable to select whether to do multipart upload or not

---

s3client.go

An error occurred in my pipeline using s3-resource.
```
0 B / 3.46 MB [------------------------------------------------------] 0.00 % 0serror running command: ConfigError: part size must be at least 5242880 bytes
```
I set `disable_mutipart: true` in source configuration.
Before, when `deisalbe_multipart` is set, upload part size is file size + 1.
https://github.com/concourse/s3-resource/blob/84741092da864119fa7bc64654804c880de4c34c/s3client.go#L202
S3 compatible provider has a minimum size of the upload part.
[Amazon S3 Multipart Upload Limits \- Amazon Simple Storage Service](https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html)
So, if the file size is smaller than this, the upload fails.
I fixed it.
Sorry, I can't write the test for these changes.
But I confirmed that this patch …

Fix upload part size when `disable_multipart` is set

---

README.md
fakes/fake_s3client.go
in/command.go
in/models.go
integration/in_test.go
integration/s3client_test.go
s3client.go

This adds a new param to `in` requests called `download_tags`. It will write the [S3 object tags](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html) as key:value pairs to `tags.json`. It is disabled by default.
The `SetTags` function on `s3client` is currently only used for testing, but it could be used to allow tags to be written in `out` (#119).

Optionally download tags when getting object

---

README.md

- godep is not used any more
- since go.mod is used, remove instructions to `go get`
- mention same Go version as in go.mod
- the name is "Go", not "golang"

doc: remove stale information from README

---

README.md
versions/versions.go
versions/versions_test.go

This PR fixes a regression introduced in https://github.com/concourse/s3-resource/pull/156.
The implementation prior to #156 had the undocumented behaviour of wrapping regexp with `^` and `$`. Unfortunately this was lost.
The first commit restore this behaviour.
The second commit ensure that whoever worked around the issue by adding explicit anchors to its regexp will not get bitten by the fix.
Third commit update the readme to explicitly state that `regexp` will be handled as anchored in all cases.
The tests passes but I haven't run the integration tests yet.

Fix regexp anchors regression

---

README.md
in/command.go
in/command_test.go

Closes: https://github.com/concourse/s3-resource/issues/154
~Still testing for now~

Add s3_uri and file_path support

---

s3client.go

Hello,
There appears to have recently been a regression in the S3 resource type due to the new progress bar code, where uploading or downloading a zero length file will cause the resource type to hang.
This is a documented issue with the progress bar library: https://github.com/vbauerster/mpb/issues/7
The solution is to manually mark the progress bar as complete with 0 length files.
We were unable to implement tests for this behaviour as the testing framework does not allow mocking the AWS Go SDK, only the s3 resource s3client, which is where the behaviour that needs to be tested is.
We have instead performed manual testing which was successful.

Fix handling of zero length files

---

README.md
cmd/check/main.go
cmd/in/main.go
cmd/out/main.go
integration/integration_suite_test.go
models.go
s3client.go
s3client_test.go

The [AWS_CA_BUNDLE](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html#envvars-list-AWS_CA_BUNDLE) environment variable can be used within the AWS SDK to set a custom CA bundle
This is particularly useful with custom S3 compatible endpoints.
Currently, if the AWS_CA_BUNDLE environment variable is set, the s3 resource will fail:
```
error error creating aws config: unable to add custom RootCAs HTTPClient, has no WithTransportOptions, *http.Client
```
This occurs because the AWS Go SDK v2 expects AWS's HTTP client to always be an `awshttp.BuildableClient`: https://github.com/aws/aws-sdk-go-v2/blob/c69bd7e10c45c4625623d29f4c7b3889188029e1/config/resolve.go#L57-L61
This pull request updates the S3 resource to use an `awshttp.BuildableClient` rather than a `http.Client`, …

Fix using s3 resource in combination with AWS_CA_BUNDLE option
